---
title: "Monocyte Macrophage trajactory"
author: "`r config::get(file = 'Config.yml')$document$author`"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: true
    latex_engine: pdflatex
    fig_caption: yes
    highlight: haddock
    number_sections: yes
knit: (
  function(inputFile, encoding) {
    Config=config::get(file = 'Config.yml') 
    
    pSubTitle <- paste0("Monocyte Macrophage trajactory",".pdf")
    
    base_output_dir <- Config$base_output_dir
 
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle,
      output_dir = base_output_dir )}
    )

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,include=T,warning=F)
```

```{r,include=F}
rm(list=ls())
#install.packages('Seurat')
library(dplyr)
library(ggplot2)
library(scran)
library(scuttle)
library(bluster)
library(SingleR)
#library("Seurat")
# sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
# sudo apt-get update
# sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
#install.packages("units")
#devtools::install_github('cole-trapnell-lab/monocle3')
```

```{r,include=T}
Config=config::get(file = 'Config.yml')
Path=Config$Path
Rawdata_path=file.path(Path, "R/Rawdata")
Rcode_path=file.path(Path, "R/Rcode")
```


```{r,include=T}
SRA_sample=read.csv(file.path(Rawdata_path,"SraRunInfo.csv" ))
SRA_sample_anno=SRA_sample[,c("LibraryName","Run")]%>%mutate(Group=c(rep("Gout_SYN",3),rep("Gout_PBMC",7),rep("Control_PBMC",5)))%>%setNames(c("Sample_ID","SRR_number","Group"))
scdata_Samples_ID2=SRA_sample[,c("LibraryName","Run")]%>%mutate(Group=c(rep("Gout_SYN",3),rep("Gout_PBMC",7),rep("Control_PBMC",5)))%>%setNames(c("Sample_ID","SRR_number","Group"))%>%mutate(Sample_ID2=c(paste0("Gout_SYN_",c(1:3)),paste0("Gout_PBMC_",c(1:7)),paste0("Control_PBMC_",c(1:5)) ))
```


```{r,include=T}
knitr::kable(scdata_Samples_ID2,caption = "Sample information")
 
```

```{r,include=F}
Main_celltype=c("B_cell","CD4+_T_cell","CD8+_T_cell","T_cell","NK_cell","Monocyte","Neutrophils","Macrophage","DC" ,"Platelets")
All_celltype_color=c(RColorBrewer::brewer.pal(n = 9, name = "Set1") ,RColorBrewer::brewer.pal(n = 2, name = "Set2"))
names(All_celltype_color)=c(Main_celltype,"Other") 
```



```{r}

if ( !file.exists(file.path(Rawdata_path,"Classic_mono_subtype_monocle.rdata"))){
# Gout_sample=Classical_mono$batch%>%.[grepl("Gout",.)]%>%unique()
 load(file.path(Rawdata_path,"Classical_mono_subtype.rdata"))
  Gout_sample=c("Gout_PBMC_1","Gout_PBMC_3","Gout_PBMC_5","Gout_PBMC_7" ) 
  sce=subset(Classical_mono_sce3,,batch%in%Gout_sample)
 
  duplicated_names =duplicated(colnames(sce)) 
  sce_unique = sce[, !duplicated_names]
  cds <-monocle3::new_cell_data_set(
     expression_data = counts(sce_unique),
    cell_metadata = colData(sce_unique)
          )

 
# If you have existing UMAP or PCA embeddings:
  reducedDims(cds) <- reducedDims(sce_unique)[c("PCA2","UMAP")]
  names(reducedDims(cds))=c("PCA","UMAP")
 # Normalize and preprocess data
  cds2 <- monocle3::preprocess_cds(cds, num_dim = 100,norm_method = c("log"),scaling = TRUE)
 # Reduce dimensionality
  cds3 <- monocle3:: reduce_dimension(cds2)
  cds4 <- monocle3:: cluster_cells(cds3)
# Learn the trajectory
  cds5 <- monocle3:: learn_graph(cds4, use_partition = F)
  cds6<- monocle3:: order_cells(cds5)
 #cds6 =monocle3::order_cells(cds5)

  P1=monocle3::plot_cells(cds6,
           color_cells_by = "Mono_subtype2",group_label_size = 3.5,
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)


  P2=monocle3::plot_cells(cds6,
           color_cells_by = "pseudotime",group_label_size = 3.5,
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)
 save(P1,P2,file=file.path(Rawdata_path,"Classic_mono_subtype_monocle.rdata"))

} else{
  
  load(file.path(Rawdata_path,"Classic_mono_subtype_monocle.rdata"))
}
```

```{r,include=T,fig.width=12,fig.height=6,include=T}
cowplot::plot_grid(P1,P2,nrow=1)
```

```{r}
knitr::knit_exit()
```


