default:
  document:
     author: "Liu cong" 
  root_path: "/media/yang/Hirbe_lab_Drive_5/Gout_scRNA"
  SRA_dir: "SRA"
  R_dir: "R"
  Rawdata_dir: "Rawdata"
  base_output_dir: "/media/yang/Hirbe_lab_Drive_5/Gout_scRNA/Report"

